package com.lwoptl.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogicForm<M extends BaseLogicForm<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setItemId(java.lang.String itemId) {
		set("item_id", itemId);
		return (M)this;
	}
	
	public java.lang.String getItemId() {
		return getStr("item_id");
	}

	public M setColumn(java.lang.String column) {
		set("column", column);
		return (M)this;
	}
	
	public java.lang.String getColumn() {
		return getStr("column");
	}

	public M setDbColmn(java.lang.String dbColmn) {
		set("db_colmn", dbColmn);
		return (M)this;
	}
	
	public java.lang.String getDbColmn() {
		return getStr("db_colmn");
	}

	public M setDataFrom(java.lang.String dataFrom) {
		set("data_from", dataFrom);
		return (M)this;
	}
	
	public java.lang.String getDataFrom() {
		return getStr("data_from");
	}

	public M setLogic(java.lang.String logic) {
		set("logic", logic);
		return (M)this;
	}
	
	public java.lang.String getLogic() {
		return getStr("logic");
	}

	public M setDataTo(java.lang.String dataTo) {
		set("data_to", dataTo);
		return (M)this;
	}
	
	public java.lang.String getDataTo() {
		return getStr("data_to");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
