package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseDataDictionaryValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionaryValue extends BaseDataDictionaryValue<DataDictionaryValue> {

}
