package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseDemo1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Demo1 extends BaseDemo1<Demo1> {
	public static final Demo1 dao = new Demo1().dao();
}
