package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseFileUploaded;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileUploaded extends BaseFileUploaded<FileUploaded> {

}
