package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseLogicTimeline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogicTimeline extends BaseLogicTimeline<LogicTimeline> {
	public static final LogicTimeline dao = new LogicTimeline().dao();
}
