package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseLogicForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogicForm extends BaseLogicForm<LogicForm> {
	public static final LogicForm dao = new LogicForm().dao();
}
