package com.lwoptl.common.model;

import com.lwoptl.common.model.base.BaseLogicItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogicItem extends BaseLogicItem<LogicItem> {
	public static final LogicItem dao = new LogicItem().dao();
}
